name: Build Image

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

permissions:
  packages: write

jobs:
  cs-docker-build-image:
    name: CS Workflow
    uses: Coto-Studio/workflows/.github/workflows/docker-build-image-v2.yml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
