name: Ghost Image - Build on Push

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-image:
    name: Ghost Image
    uses: ./.github/workflows/build-image.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
